### ISSUE TITLE
App lifecycle problems

### ISSUE THREAD

**Issue by clbemre** [Mijick/CameraView#26] opened 2024-06-24 13:37 UTC
Hello, firstly this is a great framework.

I have a problem. When the application goes to the background and comes to the front again, the image or video preview closes and returns to the shooting screen, this is a problem, the second problem is that when I try to shoot again after this scenario, I get a crash.

Why doesn't the app continue where I left off when I put it in the background and then bring it back to the foreground?

`var cameraView: UIView { cameraLayer.superview ?? .init() }` -> and i get a crash for take a picture after background/foregroung. Because I guess CameraInputView is being recreated.

Thank you

**Comment by FulcrumOne** [comment] 2024-06-24 21:13
Hey @clbemre, thanks for this ticket!

I'm currently busy developing an update for our other library ([NavigationView](https://github.com/Mijick/NavigationView)), but I'll be back here as soon as I finish that task (probably at the end of this week).

I hope it suits you, thanks again for your ticket and have a nice day,
T.K.

**Comment by clbemre** [comment] 2024-06-26 10:13
Hello again @FulcrumOne, thank you for your interest.

Additionally, when there is a **CameraPreview** screen displayed, if I display an alert on the screen with `MJCameraController().alert { }`, the **CameraPreview** closes. I want to maintain its state and prevent the preview screen from closing unless I close it myself.

**Comment by clbemre** [comment] 2024-07-01 06:38
Hello again @FulcrumOne, when will you fix these topics? or will? 

Thank you.

**Comment by FulcrumOne** [comment] 2024-07-01 08:48
hey @clbemre,

Sorry, had a lot of work related to our other libraries. In my calendar, work on this library is scheduled to start this Thursday
![CleanShot 2024-07-01 at 10 44 38](https://github.com/Mijick/CameraView/assets/23524947/5546024c-40d1-483f-b0dd-54cebc593a7f)

Apologies for the "communication issues" once again; I believe creating a Discord / Slack channel would help us stay better connected and updated on things related to libraries. I'll try to organize it this week 😉

Have a great day,
Tomasz K.

**Comment by clbemre** [comment] 2024-07-01 08:55
Thank you @FulcrumOne , I will be waiting for your response. 
Thank you for your interest. 

Have a nice day.
Best Regards

**Comment by clbemre** [comment] 2024-07-04 12:55
Hello again, @FulcrumOne , have you started this issues solutions? I'm sorry for bothering you but its a little important for me :) 
Thank you again.

**Comment by FulcrumOne** [comment] 2024-07-04 12:58
Hey, I'm starting this evening😉 Hope it will be ready by the weekend

**Comment by FulcrumOne** [comment] 2024-07-04 15:50
> Hello, firstly this is a great framework.
> 
> I have a problem. When the application goes to the background and comes to the front again, the image or video preview closes and returns to the shooting screen, this is a problem, the second problem is that when I try to shoot again after this scenario, I get a crash.
> 
> Why doesn't the app continue where I left off when I put it in the background and then bring it back to the foreground?
> 
> `var cameraView: UIView { cameraLayer.superview ?? .init() }` -> and i get a crash for take a picture after background/foregroung. Because I guess CameraInputView is being recreated.
> 
> Thank you

hey @clbemre, just to confirm - you're telling that you experienced a crash when you backgrounded the app and then returned to the foreground, correct?

**Comment by FulcrumOne** [comment] 2024-07-04 16:02
@clbemre, that second problem (with alert and crash I was able to reproduce, so I'll start from this one)

**Comment by clbemre** [comment] 2024-07-04 16:31
First of all, there are a few problems; after the first startup, it puts it in the background without doing anything, and when it comes back to the foreground, it crashes while trying to take a photo/video. Then, after showing an alert while on the preview screen, both the preview screen disappears and when I try to take a photo or video again, it crashes again, and sometimes it is because of the cameraView superView and sometimes it is because of the blurViews, but I think the problem is common, because as far as I understand, the camera manager is deinit/init and the swiftUI randomly appears on the screen. because of their renderings.  

Additionally , independently of these, the snapshot and blurview you showed while flipping the camera are turned landscape.

Sorry for my english, sometimes i use translate :)

**Comment by FulcrumOne** [comment] 2024-07-04 17:37
hey @clbemre,

No problem, English is not my native language either (it would be nice if we both spoke Polish 😅)

Could you please test the branch called 'patch-1.2.1', it should fix your problem with alert that causes the app to crash?
You should also add this method to your MCameraController - `.equatable()` (it's a temporary solution)
![CleanShot 2024-07-04 at 19 36 35](https://github.com/Mijick/CameraView/assets/23524947/e2207744-ece1-4116-8db6-2000f6f604c0)

**Comment by clbemre** [comment] 2024-07-05 07:44
Hey @FulcrumOne  this temporary solution works. Thank you. 💪🏻
Are we going to continue with this temporary solution or are you continuing to work on resolving the issue at its base? As far as I can see, you are working on memory leaks in particular.

**Comment by FulcrumOne** [comment] 2024-07-05 09:34
hey @clbemre, thanks for letting me know!

I want to spend some time today and check the library for problems with memory leaks, and then I will move on to fixing this issue with the background mode.

**Comment by clbemre** [comment] 2024-07-05 10:30
Hey @FulcrumOne , also we have a little problem :) when First launch MCameraController, the system want to permission. If I deny the system permission, the UI does not update and switch to the error view, the camera layer visible black view.

![IMG_F5B502CD1829-1](https://github.com/Mijick/CameraView/assets/7671284/1138a2f0-aaeb-4560-8ce1-e894f3a1bad8)

**Comment by FulcrumOne** [comment] 2024-07-05 17:29
@clbemre I'll have to spend little more time on this task, as the problem is little bigger than I initially thought; there are several problems that I discovered today. I'll keep you in the loop😉

**Comment by clbemre** [comment] 2024-07-05 21:46
okey @FulcrumOne  thank you for your response. I'll be wating for you. Good luck :)

**Comment by FulcrumOne** [comment] 2024-07-06 14:17
Hey @clbemre,

So we have two potential solutions to our problem:
We can move `CameraManager` to the level above (i.e. the parent view in which MCameraController is implemented, managed by the developer). Additionally if we opt for this option, I would also like to move the functions from the Public+MCameraController file lines 15 -> 43 to the CameraManager initialiser.
We can make CameraManager singleton; this will allow us to avoid major changes to the public API, however, there may be some issues when trying to port the library to iPadOS and macOS.

Therefore, I think that, in the long term, a better solution will be to implement point 1. What do you think?

**Comment by FulcrumOne** [comment] 2024-07-07 10:49
@clbemre,

The branch named `patch-1.2.1-beta` contains fixes to the following problems:
1. MCameraController and error screen
2. Alert interrupting camera session

**Comment by FulcrumOne** [comment] 2024-07-07 10:55
> Hello, firstly this is a great framework.
> 
> I have a problem. When the application goes to the background and comes to the front again, the image or video preview closes and returns to the shooting screen, this is a problem, the second problem is that when I try to shoot again after this scenario, I get a crash.
> 
> Why doesn't the app continue where I left off when I put it in the background and then bring it back to the foreground?
> 
> `var cameraView: UIView { cameraLayer.superview ?? .init() }` -> and i get a crash for take a picture after background/foregroung. Because I guess CameraInputView is being recreated.
> 
> Thank you

I cannot reproduce this problem unfortunately. However, there is a chance that this branch has already fixed the issue. If not, please let me know

**Comment by clbemre** [comment] 2024-07-07 10:57
@FulcrumOne Hello, Is the temporary solution not sufficient at the moment? 
Also I think long term solution is better.

---
patch-1.2.1-beta solutions is finished or will? 
---
`var cameraView: UIView { cameraLayer.superview ?? .init() }` -> It got resolved after applying the equatable() workaround.

Actually after I applying the equatable() all problems resolved. I guess just have a little memory leak, thats all.

**Comment by FulcrumOne** [comment] 2024-07-07 10:58
> Additionally , independently of these, the snapshot and blurview you showed while flipping the camera are turned landscape.

I'm working on this now. If you need a faster solution, I strongly recommend locking the rotation for the current screen (`lockOrientation` method).

**Comment by clbemre** [comment] 2024-07-07 11:00
> > Additionally , independently of these, the snapshot and blurview you showed while flipping the camera are turned landscape.
> 
> I'm working on this now. If you need a faster solution, I strongly recommend locking the rotation for the current screen (`lockOrientation` method).

I noticed this about this problem. When I tested it on the iPhone X, it rotates, but when I tested it on the iPhone 11 Pro Max, it does not rotate. I also completely turned off the device rotation, it only works in portrait mode.

**Comment by FulcrumOne** [comment] 2024-07-07 11:00
> @FulcrumOne Hello, Is the temporary solution not sufficient at the moment? Also I think long term solution is better.
> 
> * patch-1.2.1-beta solutions is finished or will?
> * `var cameraView: UIView { cameraLayer.superview ?? .init() }` -> It got resolved after applying the equatable() workaround.
> * Actually after I applying the equatable() all problems resolved. I guess just have a little memory leak, thats all.

This temporary solution was a bit unstable and caused other problems (the error screen was not displayed for example). I would therefore recommend using the `patch-1.2.1-beta` branch 😉

**Comment by clbemre** [comment] 2024-07-07 11:01
> > @FulcrumOne Hello, Is the temporary solution not sufficient at the moment? Also I think long term solution is better.
> > 
> > * patch-1.2.1-beta solutions is finished or will?
> > * `var cameraView: UIView { cameraLayer.superview ?? .init() }` -> It got resolved after applying the equatable() workaround.
> > * Actually after I applying the equatable() all problems resolved. I guess just have a little memory leak, thats all.
> 
> This temporary solution was a bit unstable and caused other problems (the error screen was not displayed for example). I would therefore recommend using the `patch-1.2.1-beta` branch 😉

Okey I will, thank you for your interest and for this great library :)

**Comment by FulcrumOne** [comment] 2024-07-07 11:10
Thanks! If you have any further problems, let me know😉

PS. Check out our other solutions too!

**Comment by clbemre** [comment] 2024-07-08 07:32
Hello @FulcrumOne , So now we can create **MJCameraController(manager: .init())**, is it correct?

**Comment by clbemre** [comment] 2024-07-08 07:38
@FulcrumOne and , I applied **patch-1.2.1-beta**. but if i remove Equatable and .equatable() modifier, still i am getting crash, I guess, its have to stay, is it correct?

**Comment by FulcrumOne** [comment] 2024-07-08 09:36
hey @clbemre,

1. Sorry, my fault I had forgotten to tell you how to use it 😅
![CleanShot 2024-07-08 at 11 27 49](https://github.com/Mijick/CameraView/assets/23524947/140dd71f-e4f6-4e01-9d2f-4cab9e61e86b)

This way (or you can use StateObject, it depends on what your view looks like). No, you don't need to use equatable anymore, because throwing that manager out there means that the parent view is responsible for keeping that object alive.

2. Yes, I'm aware of this problem with UI freezing after changing the output type; it's already fixed, but you have to give me an hour or two, because it's connected to a screen rotation bug fix, and I need test the whole solution first 😉

3. About using `weak self` - this will be very controversial, but I did it in this way, because using weak connections to the objects (or optional unwrapping) would mask the potential problems with objects management; in another words, my thinking was it's better to see the app crashing and know that there's a problem with the library than to waste the time locating the source of the problem

**Comment by clbemre** [comment] 2024-07-08 09:53
@FulcrumOne  Thank you, I'll check, I just wondered createCameraController() like this CameraController(manager: manager)?

**Comment by FulcrumOne** [comment] 2024-07-08 09:56
@clbemre, exactly. And those attributes you see in the `CameraManager` initialiser are the initial values with which you start the camera instance

**Comment by clbemre** [comment] 2024-07-08 09:58
@FulcrumOne I understand. I just wondered again 😀  Is CameraView start point, right? Shouldn't manager be https://github.com/StateObject?

**Comment by FulcrumOne** [comment] 2024-07-08 10:03
you can use either - it depends on what your view hierarchy looks like 😉

**Comment by clbemre** [comment] 2024-07-08 10:04
@FulcrumOne thank you I'll be waiting for you, for fix.

**Comment by clbemre** [comment] 2024-07-08 11:07
I don't know if you noticed but the grid is not visible. :/

**Comment by FulcrumOne** [comment] 2024-07-08 11:18
There are still some minor UI bugs I'm working on (but the problem with grid should be resolved)

**Comment by clbemre** [comment] 2024-07-08 12:19
@FulcrumOne I have checked just before and applied. But still;

- grid not visible ❌ ( maybe i have missed one thing, i don't know :/ )
- UI freezing works correct ✅ ( Im not sure but i guess rarely works wrong)
- first open is fast now ✅
- flip rotate animation works correct. ✅

thank you 🙏🏻

**Comment by clbemre** [comment] 2024-07-08 12:20
sorry, also The UI update failure error regarding system permission denial also persists.

**Comment by FulcrumOne** [comment] 2024-07-08 12:25
are you sure you are using the patch-1.2.1-beta branch? On my phone, I don't see the problems described

**Comment by FulcrumOne** [comment] 2024-07-08 12:27
Ok, I was able to see the second problem, but the one with the invisible grid I still cannot debug

**Comment by clbemre** [comment] 2024-07-08 12:56
I have tried it on 2 different real devices, the grids do not appear neither at the first startup nor with the on/off grid button. 😬

**Comment by clbemre** [comment] 2024-07-08 12:59
I'm sorry :/ but Also, something like this happens, I start recording a video and the screen refreshes at that moment and the video starts recording, normally it would start directly. But now, because the screen is refreshing, the frame before I press the button appears on the screen momentarily and disappears, a UI bug. 😥

**Comment by FulcrumOne** [comment] 2024-07-08 13:00
could you show me a video please?

**Comment by clbemre** [comment] 2024-07-08 13:07
https://github.com/Mijick/CameraView/assets/7671284/1fac686b-128a-4ae6-b16e-7340438caa46

@FulcrumOne

**Comment by clbemre** [comment] 2024-07-08 13:17
Ah sorry, some things its gone my branch, I'll check again.

**Comment by clbemre** [comment] 2024-07-08 13:26
https://github.com/Mijick/CameraView/assets/7671284/05f85df7-9dd4-4dc5-86ba-504aab3c5cd4

@FulcrumOne 

I took a more clear video, focus on the bottom left corner and notice a momentary view appearing and disappearing. , can you take a quick look? because I'm going to delete it :D

**Comment by FulcrumOne** [comment] 2024-07-08 16:22
> sorry, also The UI update failure error regarding system permission deny also persists.

should be fixed now

**Comment by FulcrumOne** [comment] 2024-07-08 16:26
> 346579937-05f85df7-9dd4-4dc5-86ba-504aab3c5cd4.mov 
> 
> @FulcrumOne
> 
> I took a more clear video, focus on the bottom left corner and notice a momentary view appearing and disappearing. , can you take a quick look? because I'm going to delete it :D

Oh, now I see it. i'll try to fix it this night, and if I don't fix it then, I'll have to move it to Wednesday unfortunately😉

**Comment by clbemre** [comment] 2024-07-08 16:37
@FulcrumOne okey thank you again 🙏

**Comment by FulcrumOne** [comment] 2024-07-08 16:54
Btw, just to be sure, because the both problems (invisible grids and flashing views) are not present in demo app I'm using for testing; are you sure it's not caused by some UI elements of your app? 

And if so, could you please prepare the code for me that I can use to reproduce the bug? Thanks in advance! 😅

**Comment by clbemre** [comment] 2024-07-08 17:00
I can check again, but firstly could you send me your demo project ?

**Comment by FulcrumOne** [comment] 2024-07-08 17:06
@clbemre,

https://github.com/Mijick/CameraView-Demo, branch `patch-2.0.0`

**Comment by clbemre** [comment] 2024-07-09 09:33
@FulcrumOne Hey I have found issue, The problem was caused by me, when I pressed the record button, I was setting captureSession.sessionPreset = .hd1280x720. This was causing a rendering problem on the screen. It was fixed when I deleted the code. Also, the system permission alert problem and the gird visibility problem were solved. Everything is perfect now, thank you very much for your interest. We don't have any other problems that I know of. 🙏🏻🙏🏻

**Comment by FulcrumOne** [comment] 2024-07-09 11:26
@clbemre,

I'm super glad to hear it! I'll fix some other bugs I noticed and release version 2.0.0. Thanks for your support and see you soon!⚡️

**Comment by clbemre** [comment] 2024-07-09 11:28
Thank you. 🙏 I’ll be waiting for 2.0.0 :) Good luck

Have a nice day.

**Comment by clbemre** [comment] 2024-07-11 09:55
Hello again @FulcrumOne , in CameraManager, you add observers but you don't remove. maybe you can add
deinit{
NotificationCenter.default.removeObserver(self, name: .AVCaptureSessionWasInterrupted, object: captureSession)
}

**Comment by FulcrumOne** [comment] 2024-07-11 10:39
@clbemre,

Ahh, you're literally a life saver. I totally missed it. Thanks!

**Comment by clbemre** [comment] 2024-07-11 12:39
@FulcrumOne 

Haha, every time, thank you too:)

**Comment by FulcrumOne** [comment] 2024-07-11 19:01
@clbemre,

Fixed! I also changed the rotation animation a bit + fixed some other issues. Could you please check the latest commits and give me your feedback? Thanks a lot!

**Comment by clbemre** [comment] 2024-07-12 22:36
@FulcrumOne Hey, I'll check as soon as. Thank you for the information.

**Comment by clbemre** [comment] 2024-07-12 23:44
@FulcrumOne Hello again, everything is good. but just i want to say something.
 
When I rotate to landscape mode my phone, the camera lens changes and goes into close-up mode. It would be better if this was optional, because I don't want it to go into close-up mode when I rotate it landscape. If there is a option, I don't know, I didn't see. :) Other than that, everything is fine, well done.

**Comment by FulcrumOne** [comment] 2024-07-13 08:46
Hey, could you show me the video of the problem you described? Thanks!

**Comment by clbemre** [comment] 2024-07-13 10:18
@FulcrumOne Sorry I had turned some things off. So I couldn't re-run the error scenario. If I encounter this error again, I will let you know.

**Comment by FulcrumOne** [comment] 2024-07-13 17:09
@clbemre, thanks!

**Closed** 2024-07-15 09:45 UTC
Labels: bug
